name: wan_android_flutter
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # 状态管理
  provider: ^6.1.5
  # 屏幕适配相关
  flutter_screenutil: ^5.9.3
  # 网络请求
  dio: ^5.8.0+1
  # cookie持久化
  dio_cookie_manager: ^3.2.0
  cookie_jar: ^4.0.8
  # toast提示
  oktoast: ^3.4.0
  # 获取版本信息设备信息等
  package_info_plus: ^8.3.0
  device_info_plus: ^11.4.0
  # 权限申请
  permission_handler: ^12.0.0+1
  # 跳转到外部应用、scheme
  url_launcher: ^6.3.1
  # 本地化存储
  shared_preferences: ^2.5.3
  # banner轮播图组件
  flutter_swiper_view: ^1.1.8
  # 图片缓存加载
  cached_network_image: ^3.4.1
  # 一个 Flutter 插件，允许您添加内联 webview，使用无头 webview 以及打开应用程序内浏览器窗口
  # https://github.com/pichillilorenzo/flutter_inappwebview
  flutter_inappwebview: ^6.1.5
  # 显示html文本内容的组件
  flutter_html: ^3.0.0
  # 下拉刷新上拉加载
  pull_to_refresh: ^2.0.0
  # 图片选择插件 https://github.com/flutter/packages/tree/main/packages/image_picker
  image_picker: ^1.1.2
  webview_flutter: 4.8.0
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^4.2.0
  marquee_plus: ^2.2.4

  get: ^4.7.2

  flutter_localization: ^0.3.2

  # https://juejin.cn/post/7508945084487401526#heading-19 推荐的框架
  extended_image: ^10.0.1
  event_bus: ^2.0.1
  uuid: ^4.5.1
  path_provider: ^2.1.5
  flutter_svg: ^2.1.0
  easy_refresh: ^3.4.0
  scroll_to_index: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter:

  uses-material-design: true
  assets:
    - assets/images/

