name: wan_android_flutter
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # 状态管理
  provider: ^6.1.5
  # 屏幕适配相关
  flutter_screenutil: ^5.9.3
  # 网络请求
  dio: ^5.8.0+1
  # cookie持久化
  dio_cookie_manager: ^3.2.0
  cookie_jar: ^4.0.8
  # toast提示
  oktoast: ^3.4.0
  # 获取版本信息设备信息等
  package_info_plus: ^8.3.0
  device_info_plus: ^11.4.0
  # 权限申请
  permission_handler: ^12.0.0+1
  # 跳转到外部应用、scheme
  url_launcher: ^6.3.1
  # 本地化存储
  shared_preferences: ^2.5.3
  # banner轮播图组件
  flutter_swiper_view: ^1.1.8
  # 图片缓存加载
  cached_network_image: ^3.4.1
  # webview：基于原生webview封装的
  flutter_inappwebview: ^6.1.5
  # 显示html文本内容的组件
  flutter_html: ^3.0.0
  # 下拉刷新上拉加载
  pull_to_refresh: ^2.0.0

  get: ^4.7.2


  # https://juejin.cn/post/7508945084487401526#heading-19 推荐的框架
  fluttertoast: ^8.2.12
  extended_image: ^10.0.1
  event_bus: ^2.0.1
  uuid: ^4.5.1
  path_provider: ^2.1.5
  flutter_svg: ^2.1.0
  easy_refresh: ^3.4.0
  scroll_to_index: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter:

  uses-material-design: true
  assets:
    - assets/images/

