import 'package:get/get.dart';

class AppStrings {
  static const Map<String, Map<String, String>> localizedValues = {
    'zh': {
      'app_name': '玩安卓',
      'settings': '设置',
      'dark_mode': '深色模式',
      'follow_system': '跟随系统',
      'light': '浅色',
      'dark': '深色',
      'language': '语言',
      'privacy_policy': '隐私政策',
      'user_agreement': '用户协议',
      'clear_cache': '清除缓存',
      'version_info': '版本信息',
      'clear_cache_confirm': '确定要清除所有缓存吗？',
      'cancel': '取消',
      'confirm': '确定',
      'cache_cleared': '缓存已清除',
      'select_dark_mode': '选择深色模式',
      'select_language': '选择语言',
      'theme_color': '主题色',
      'select_theme_color': '选择主题色',
      'chinese': '中文',
      'english': 'English',
      'general_settings': '通用设置',
      'privacy_security': '隐私与安全',
      'other': '其他',
      'click_login': '点击登录',
      'level_super_member': '等级: 超级会员',
      'my_collection': '我的收藏',
      'check_update': '检查更新',
      'about_us': '关于我们',
      'logout': '退出登录',
      'already_latest_version': '已是最新版本',
      'scan_qr_hint': '将二维码放入框内扫描',
      'scan_success': '扫描成功',
      'copied_to_clipboard': '已复制到剪切板',
      'scan': '扫一扫',
      'anonymous': '匿名',
      'search_hot_key': '搜索热词',
      'common_website': '常用网站',
      'pull_down_refresh': '下拉刷新',
      'release_refresh': '释放刷新',
      'refreshing': '刷新中...',
      'refresh_complete': '刷新完成',
      'refresh_failed': '刷新失败',
      'loading': '加载中...',
      'release_load': '释放加载',
      'pull_up_load_more': '上拉加载更多',
      'no_more_data': '没有更多数据',
      'load_failed': '加载失败',
      'search_hint': '搜索文章/项目/博主',
      'pinned': '置顶',
      'app_full_name': '玩安卓 Flutter',
      'version': '版本',
      'app_description': '持续学习中 · 努力提升中',
      'app_features': '应用功能',
      'feature_home_title': '首页资讯',
      'feature_home_desc': '获取最新的安卓开发资讯和技术文章',
      'feature_knowledge_title': '知识体系',
      'feature_knowledge_desc': '系统化学习安卓开发知识，构建完整知识体系',
      'feature_collection_desc': '收藏喜欢的文章，方便随时查看和学习',
      'feature_profile_title': '个人中心',
      'feature_profile_desc': '管理个人信息，查看学习记录和成就',
      'developer_info': '开发者信息',
      'developer': '开发者',
      'developer_name': '今生挥毫只为你',
      'other_info': '其他信息',
      'copyright_info': '版权信息',
      'copyright_value': '© 2026 玩安卓 Flutter',
      'open_source_license': '开源协议',
      'mit_license': 'MIT License',
      'current_latest_version': '当前已是最新版本',
      'keep_learning': '持续学习 · 不断进步',
      'login': '登录',
      'register': '注册',
      'account': '账号',
      'password': '密码',
      'confirm_password': '确认密码',
      'input_account_hint': '请输入您的账号',
      'input_password_hint': '请输入您的密码',
      'input_password_again_hint': '请再次输入密码',
      'no_account_hint': '还没有账号？',
      'register_now': '立即注册',
      'new_version_found': '发现新版本',
      'update_content': '更新内容',
      'update_item_1': '优化用户体验，提升应用性能',
      'update_item_2': '修复已知问题，增强稳定性',
      'update_item_3': '新增多项实用功能',
      'update_item_4': '界面全面升级，视觉更清爽',
      'later': '稍后再说',
      'update_now': '立即更新',
      'download_page': '下载页面',
      'clear': '清空',
      'clear_input_hint': '清空输入框',
      'password_visibility_toggle': '密码可见开关',
      'password_visibility_hint': '密码是否可见',
      'get_verification_code': '获取验证码',
    },
    'en': {
      'app_name': 'WanAndroid',
      'settings': 'Settings',
      'dark_mode': 'Dark Mode',
      'follow_system': 'Follow System',
      'light': 'Light',
      'dark': 'Dark',
      'language': 'Language',
      'privacy_policy': 'Privacy Policy',
      'user_agreement': 'User Agreement',
      'clear_cache': 'Clear Cache',
      'version_info': 'Version Info',
      'clear_cache_confirm': 'Are you sure to clear all cache?',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'cache_cleared': 'Cache cleared',
      'select_dark_mode': 'Select Dark Mode',
      'select_language': 'Select Language',
      'theme_color': 'Theme Color',
      'select_theme_color': 'Select Theme Color',
      'chinese': 'Chinese',
      'english': 'English',
      'general_settings': 'General',
      'privacy_security': 'Privacy & Security',
      'other': 'Other',
      'click_login': 'Tap to login',
      'level_super_member': 'Level: Super Member',
      'my_collection': 'My Collection',
      'check_update': 'Check Update',
      'about_us': 'About Us',
      'logout': 'Logout',
      'already_latest_version': 'Already the latest version',
      'scan_qr_hint': 'Place QR code in the frame',
      'scan_success': 'Scan successful',
      'copied_to_clipboard': 'Copied to clipboard',
      'scan': 'Scan',
      'anonymous': 'Anonymous',
      'search_hot_key': 'Hot Search',
      'common_website': 'Common Websites',
      'pull_down_refresh': 'Pull down to refresh',
      'release_refresh': 'Release to refresh',
      'refreshing': 'Refreshing...',
      'refresh_complete': 'Refresh complete',
      'refresh_failed': 'Refresh failed',
      'loading': 'Loading...',
      'release_load': 'Release to load',
      'pull_up_load_more': 'Pull up for more',
      'no_more_data': 'No more data',
      'load_failed': 'Load failed',
      'search_hint': 'Search articles/projects/authors',
      'pinned': 'Pinned',
      'app_full_name': 'WanAndroid Flutter',
      'version': 'Version',
      'app_description': 'Keep learning · Keep improving',
      'app_features': 'App Features',
      'feature_home_title': 'Home News',
      'feature_home_desc': 'Get the latest Android development news and articles',
      'feature_knowledge_title': 'Knowledge System',
      'feature_knowledge_desc': 'Learn Android development systematically',
      'feature_collection_desc': 'Collect favorite articles for easy access',
      'feature_profile_title': 'Profile',
      'feature_profile_desc': 'Manage personal info and learning records',
      'developer_info': 'Developer Info',
      'developer': 'Developer',
      'developer_name': '今生挥毫只为你',
      'other_info': 'Other Info',
      'copyright_info': 'Copyright',
      'copyright_value': '© 2026 WanAndroid Flutter',
      'open_source_license': 'License',
      'mit_license': 'MIT License',
      'current_latest_version': 'Already the latest version',
      'keep_learning': 'Keep learning · Keep improving',
      'login': 'Login',
      'register': 'Register',
      'account': 'Account',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'input_account_hint': 'Please enter your account',
      'input_password_hint': 'Please enter your password',
      'input_password_again_hint': 'Please enter password again',
      'no_account_hint': "Don't have an account?",
      'register_now': 'Register Now',
      'new_version_found': 'New Version Available',
      'update_content': "What's New",
      'update_item_1': 'Improved user experience and performance',
      'update_item_2': 'Fixed known issues, enhanced stability',
      'update_item_3': 'Added multiple practical features',
      'update_item_4': 'UI completely upgraded, cleaner look',
      'later': 'Later',
      'update_now': 'Update Now',
      'download_page': 'Download Page',
      'clear': 'Clear',
      'clear_input_hint': 'Clear input field',
      'password_visibility_toggle': 'Password visibility toggle',
      'password_visibility_hint': 'Toggle password visibility',
      'get_verification_code': 'Get Code',
    },
  };

  static String getString(String key) {
    final code = Get.locale?.languageCode ?? 'zh';
    return localizedValues[code]?[key] ?? localizedValues['zh']?[key] ?? key;
  }
}
